### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by grumpyseal** [corenova/yang-forge#1]
I have tried install via npm and also git cloned and npm install.
This is the output that I get:
npm ERR! addLocal Could not install /Users/grumpyseal/.nvm/versions/node/v0.12.4/yangforge@_/yang_modules/complex-types
npm WARN optional dep failed, continuing complex-types@file:yang_modules/complex-types
npm ERR! addLocal Could not install /Users/grumpyseal/.nvm/versions/node/v0.12.4/yangforge@_/yang_modules/opnfv-promise
npm WARN optional dep failed, continuing opnfv-promise@file:yang_modules/opnfv-promise
/Users/grumpyseal/.nvm/versions/node/v0.12.4/bin/yangforge -> /Users/grumpyseal/.nvm/versions/node/v0.12.4/lib/node_modules/yangforge/bin/yfc
yangforge@0.9.1 /Users/grumpyseal/.nvm/versions/node/v0.12.4/lib/node_modules/yangforge
├── colors@1.1.2
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── prettyjson@1.1.2 (colors@0.6.2, minimist@1.1.0)
├── errorhandler@1.4.1 (escape-html@1.0.2, accepts@1.2.11)
├── passport@0.2.2 (pause@0.0.1, passport-strategy@1.0.0)
├── express@4.13.1 (escape-html@1.0.2, merge-descriptors@1.0.0, array-flatten@1.1.0, cookie@0.1.3, utils-merge@1.0.0, cookie-signature@1.0.6, methods@1.1.1, fresh@0.3.0, range-parser@1.0.2, path-to-regexp@0.1.6, vary@1.0.1, content-type@1.0.1, etag@1.7.0, parseurl@1.3.0, content-disposition@0.5.0, serve-static@1.10.0, depd@1.0.1, on-finished@2.3.0, finalhandler@0.4.0, qs@4.0.0, debug@2.2.0, proxy-addr@1.0.8, send@0.13.0, type-is@1.6.5, accepts@1.2.11)
└── body-parser@1.13.2 (bytes@2.1.0, content-type@1.0.1, depd@1.0.1, qs@4.0.0, on-finished@2.3.0, http-errors@1.3.1, raw-body@2.1.2, debug@2.2.0, type-is@1.6.5, iconv-lite@0.4.11)
[grumpyseal@Grumpy128 ~]$ yfc
-bash: /Users/grumpyseal/.nvm/versions/node/v0.12.4/bin/yfc: No such file or directory

**Comment by sekur** [comment]
@grumpyseal I've replicated your issue using npm 2.10.1 and fixed up some package.json dependencies between the internal components.  It looks like npm was publishing the .coffee source instead of prepublish compiled .js if *.coffee wasn't in .npmignore file for `yang-v1-extensions`.  Not sure why it was doing that but it seemed to have been fixed in npm 2.13

In any event, I've fixed for 2.10.1 behavior so it should work now, please give it a try.

**Comment by grumpyseal** [comment]
This is what I am getting now.
npm install -g yangforge
npm ERR! addLocal Could not install /Users/grumpyseal/.nvm/versions/node/v0.12.4/yangforge@_/yang_modules/complex-types
npm WARN optional dep failed, continuing complex-types@file:yang_modules/complex-types
npm ERR! addLocal Could not install /Users/grumpyseal/.nvm/versions/node/v0.12.4/yangforge@_/yang_modules/opnfv-promise
npm WARN optional dep failed, continuing opnfv-promise@file:yang_modules/opnfv-promise
/Users/grumpyseal/.nvm/versions/node/v0.12.4/bin/yangforge -> /Users/grumpyseal/.nvm/versions/node/v0.12.4/lib/node_modules/yangforge/bin/yfc
yangforge@0.9.2 /Users/grumpyseal/.nvm/versions/node/v0.12.4/lib/node_modules/yangforge
├── colors@1.1.2
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── passport@0.2.2 (pause@0.0.1, passport-strategy@1.0.0)
├── prettyjson@1.1.2 (colors@0.6.2, minimist@1.1.0)
├── errorhandler@1.4.1 (escape-html@1.0.2, accepts@1.2.11)
├── express@4.13.1 (escape-html@1.0.2, merge-descriptors@1.0.0, array-flatten@1.1.0, cookie@0.1.3, utils-merge@1.0.0, cookie-signature@1.0.6, methods@1.1.1, fresh@0.3.0, range-parser@1.0.2, path-to-regexp@0.1.6, vary@1.0.1, content-type@1.0.1, etag@1.7.0, parseurl@1.3.0, content-disposition@0.5.0, serve-static@1.10.0, depd@1.0.1, on-finished@2.3.0, finalhandler@0.4.0, qs@4.0.0, debug@2.2.0, proxy-addr@1.0.8, send@0.13.0, accepts@1.2.11, type-is@1.6.5)
└── body-parser@1.13.2 (bytes@2.1.0, content-type@1.0.1, depd@1.0.1, on-finished@2.3.0, http-errors@1.3.1, raw-body@2.1.2, qs@4.0.0, debug@2.2.0, type-is@1.6.5, iconv-lite@0.4.11)
[grumpyseal@Grumpy128 ~]$ yfc -h
/Users/grumpyseal/.nvm/versions/node/v0.12.4/lib/node_modules/yangforge/node_modules/yang-v1-extensions/node_modules/yangforge/lib/compiler/compiler.js:153
                  Meta.copy(context, submod != null ? submod.extract('exports'
                                                             ^
TypeError: undefined is not a function
    at /Users/grumpyseal/.nvm/versions/node/v0.12.4/lib/node_modules/yangforge/node_modules/yang-v1-extensions/node_modules/yangforge/lib/compiler/compiler.js:153:62
    at Array.map (native)
    at _Class.YangCompiler.preprocess (/Users/grumpyseal/.nvm/versions/node/v0.12.4/lib/node_modules/yangforge/node_modules/yang-v1-extensions/node_modules/yangforge/lib/compiler/compiler.js:147:62)
    at _Class.YangCompiler.compile (/Users/grumpyseal/.nvm/versions/node/v0.12.4/lib/node_modules/yangforge/node_modules/yang-v1-extensions/node_modules/yangforge/lib/compiler/compiler.js:217:22)
    at _Class.<anonymous> (/Users/grumpyseal/.nvm/versions/node/v0.12.4/lib/node_modules/yangforge/node_modules/yang-v1-extensions/node_modules/yangforge/lib/compiler/compiler.js:191:25)
    at _Class.Meta.fork (/Users/grumpyseal/.nvm/versions/node/v0.12.4/lib/node_modules/yangforge/node_modules/yang-v1-extensions/node_modules/yangforge/node_modules/data-synth/lib/meta.js:358:64)
    at _Class.YangCompiler.compile (/Users/grumpyseal/.nvm/versions/node/v0.12.4/lib/node_modules/yangforge/node_modules/yang-v1-extensions/node_modules/yangforge/lib/compiler/compiler.js:181:21)
    at Function.<anonymous> (/Users/grumpyseal/.nvm/versions/node/v0.12.4/lib/node_modules/yangforge/node_modules/yang-v1-extensions/node_modules/yangforge/lib/yangforge.js:180:77)
    at Function.Meta.configure (/Users/grumpyseal/.nvm/versions/node/v0.12.4/lib/node_modules/yangforge/node_modules/yang-v1-extensions/node_modules/yangforge/node_modules/data-synth/lib/meta.js:78:13)
    at /Users/grumpyseal/.nvm/versions/node/v0.12.4/lib/node_modules/yangforge/node_modules/yang-v1-extensions/node_modules/yangforge/node_modules/data-synth/lib/data-synth.js:55:20

**Comment by sekur** [comment]
ok, recent change didn't quite do what I expected. latest update is 0.9.4 and updated in git/npm.  please give it a try - reopening.

**Comment by grumpyseal** [comment]
Well,
now I can at least do yfc -h and get output. Any ideas around this now.
I also noticed that the opnfv-promise project looks like the yang-storm
project. Is this intentional? Can you make the complex-types and the
opnfv-promise project npm modules that can be install via npm?

grumpyseal@Grumpy128 ~]$ npm install -g yangforge
npm ERR! addLocal Could not install
/Users/grumpyseal/.nvm/versions/node/v0.12.4/yangforge@
*/yang_modules/complex-types
npm WARN optional dep failed, continuing complex-types@file
:yang_modules/complex-types
npm ERR! addLocal Could not install
/Users/grumpyseal/.nvm/versions/node/v0.12.4/yangforge@
*/yang_modules/opnfv-promise
npm WARN optional dep failed, continuing opnfv-promise@file
:yang_modules/opnfv-promise
/Users/grumpyseal/.nvm/versions/node/v0.12.4/bin/yangforge ->
/Users/grumpyseal/.nvm/versions/node/v0.12.4/lib/node_modules/yangforge/bin/yfc

**Comment by sekur** [comment]
No worries on the failed "optional" dependencies for now, they were placeholders and the plan is to move them out into separate repos.

Since the error can be misleading, let me take it out of the package.json for now. 

I'm working on bundling in complex-types module as part of yangforge but opnfv-promise module will be hosted separately with stuff from some older projects fused together.  Next on my list of todos.

You should be good to go once yfc -h produces the right output.

Peter Lee

**Comment by sekur** [comment]
ok, removed optionalDependencies from yangforge for now, bump to 0.9.5 and published to npm.  The install should look cleaner now.

**Comment by grumpyseal** [comment]
I really appreciate the help. Have a great day.

Kevin Ethridge

**Comment by sekur** [comment]
No problem - please keep the bugs & feedback coming :-)

Oh FYI, schema "import" extension is currently broken - will be reworking that shortly. 

Peter Lee
