### ISSUE TITLE
-e switch seems broken, example fails

### ISSUE THREAD

**Issue by uabhabm** [corenova/yang-forge#28]
Running on latest branch (0.10.X) and testing examples fails,

 yfc schema -e 'module hello-world { description "a test"; leaf hello { type string; default "world"; } }'

->

AssertionError: unable to validate passed in '' as type 'array' with errors: undefined

Running with debug shows this error happens just after 
Thu Oct 29 2015 11:38:41 GMT+0100 (CET) LOG [forge] executing rpc schema...

**Comment by sekur** [comment]
Thanks for reporting this issue.  Looks like I inadvertently added a constraint for _min-elements 1_ for the arguments to the **schema** rpc call inside yangforge.yang schema.  Check the commit for the details.
