### ISSUE TITLE
yangforge.yaml file is referred in the README.md file.,which is not accessible(dead link)

### ISSUE THREAD

**Issue by sureshkvl** [corenova/yang-forge#30]
In the README.md Document below section,   yangforge.yaml link is not accessible.

"The corresponding actions for each of the rpc extensions are implemented inside the YangForge YAML module yangforge.yaml."

somemore dead links

cli
express
restjson
websocket
cli-example

**Comment by sekur** [comment]
@sureshkvl thanks for reporting the doc link issues.  The latest commit should fix them.
