### ISSUE TITLE
leafref and identityref support

### ISSUE THREAD

**Issue by SCAviat** [corenova/yang-forge#33]
Are these supported? They seem to be missing from the RFC6020 Coverage page https://github.com/saintkepha/yangforge/blob/master/core/yang-v1-extensions.md

If they are not, they are important features that should be added in as a priority.

Thanks for the good work.

**Comment by sekur** [comment]
Yes, they are supported.  They're not referenced in the extensions documentation since identityref and leafref are _built-in types_ and not actually language extension statements.  I probably should have a section in the documentation that explicitly lists th supported built-in types.

**Comment by SCAviat** [comment]
Glad to hear that it is supported. They are defined in RFC6020 - the heading in that page says RFC6020 Coverage, so it would be helpful if documented.

Additional question: Is there any document that describes the binding transformation process, i.e. the rules governing how different YANG language elements are transformed into JS data structures? For example I am very curious how and what into YangForge would transform a list of list containing two leafref(s) and other basictype leafs?

Also if I need to modify the way the data structures are generated (to glue it to a pre-existing framework), what is the best way to get started? 

Thank you.

**Comment by sekur** [comment]
Yeah, I'm keeping this issue open to remind myself to update the coverage documentation.

I'm actually in the middle of some major internal restructuring to make it much easier to programmatically alter the synthesis behavior. 

Take a look at github.com/saintkepha/yang-js

I'm currently splitting out the compiler from YF to make it easier for folks to consume the compiler natively as a library and I haven't released the version of YF with the new change but this will be taking place in a few days. 

The yang-js compiler library provides ability to .load specifications and schemas.  

The defaults for the YANG v1 schema and spec are found in the root folder of yang-js repo. 

The spec file is a YAML document that includes various language extensions, cardinality rules, and preprocess/construct transform functions. 

By default, it uses the "data-synth" library to synthesize various classes for representing YANG language extensions.  You can easily .load a new specification and override the transform functions to generate the data structure you'd like to produce. 

Unfortunately, this also has not been documented but I'm always open to a PR with enhanced docs. :-)

**Comment by SCAviat** [comment]
That is excellent news. That is a very nice direction you are taking YangForge.

A bit out of topic, how do you compare your approach with pyangbind (target language difference aside), philosophical differences, current capabilities and maturity?

**Comment by sekur** [comment]
Well, I think YF is far more mature than pyangbind at this stage of the game since YF has been in development for a bit over a year and has gone through 50+ releases to date.  One of my main focus has been to maintain a very clean core with maximum extensibility so that would be obvious when comparing the code bases. 

Also, YF is designed for dynamic runtime execution, so it skips the code generation step and immediately returns instantiable class hierarchy.

Another key use case was to take advantage of it being JavaScript code to enable it to seamlessly operate on the web browser as well as on the backend.

But having said that, pyang itself is a really great tool and I personally think it does a much better job (compared to YF) when purely working with YANG schemas for validations, etc.

**Comment by sekur** [comment]
I've updated the coverage doc in the [yang-js compiler](http://github.com/saintkepha/yang-js) repo to include the supported built-in types.  I'll close this issue but we can also continue our chat in gitter.

One other key highlight of YF over other _generator_ tools is the availability of built-in interface generators.

Also, the upcoming 0.12.x release of YF (any day now...) will also transition the role of YF from a fancy module compiler/runtime into a multi-module composer.  I've been tirelessly working on this new _composition_ shift for the past couple of months and I think this will greatly progress the type of applications you can create and model using YF.
