### ISSUE TITLE
example does not work as described

### ISSUE THREAD

**Issue by javadoug** [corenova/yang-forge#8]
@saintkepha Peter, the example from the README.md does not work. Note: I only tried this one example, as I thought it was closest to what I needed.

JavaScript:

```
var fs = require('fs');
var Forge = require('yangforge');
var schema = fs.readFileSync('./hello-world.yang', {encoding: 'utf-8'});
console.log(schema);
var forgery = new Forge();
var HelloWorld = forgery.compile(schema);
console.log(HelloWorld);
var test = new HelloWorld();
console.log(test.get('hello'));
test.set('hello', 'there');
console.log(test.get('works'));

Output:
(nothing is output)
```

For assurance that yangforge is installed correctly, etc. the yfc command line will, for example, generate JSON.

```
cmd>yfc schema -c hello-world.yang -f json

Output:
{
  "module": {
    "hello-world": {
      "description": "a test",
      "leaf": {
        "hello": {
          "type": "string",
          "default": "world"
        }
      }
    }
  }
}
```

WORKAROUND: I can use the command line tool (yfc) as a solution for my needs.

ASIDE:  Thanks for the pointer to this project and for your good work on it.

**Comment by sekur** [comment]
@javadoug thanks for bringing up this issue.  I've updated the README to reflect the proper usage example.  The compile output is a _wrapper_ around the compiled module so when you perform `get/set` operations, you will need to include the module name as part of the scope.  

``` javascript
test.get('hello-world.hello');
test.set('hello-world.hello', 'there');
```

Please refer to the updated README as updated likewise.

**Comment by javadoug** [comment]
@saintkepha I updated my code accordingly and still nothing. I suspect this may be an environment issue. I notice that simply importing yangforge prevents any console output from showing up. For example,

```
var fs = require('fs');
var Forge = require('yangforge');
var schema = fs.readFileSync('./hello-world.yang', {encoding: 'utf-8'});
console.log('schema: ', schema);

Output:
(nothing is output)
```

I would expect at least the string literal 'schema: ' to be output. However, if I comment out the yangforge import the file contents will output as expected. I'm using node v0.12.7 and npm v2.11.3 on a OS X v10.10.4.

**Comment by sekur** [comment]
Oh right... By default yangforge suppresses all output to console.log.  You will need to change to console.info instead. 

This is due to lazy use of logging utility (for differentiated log output) on my part.  Sorry about that, this probably also has unintended consequences on the programmatic usage of yangforge as a library. I will need to localize the console.log override to be local to yangforge only and not impact the overall process.  

So... nothing wrong with your env on your end. 

Peter Lee

**Comment by sekur** [comment]
@javadoug latest commit/publish should have addressed this issue.  console.log is no longer being suppressed by default and only when running in the context of `yfc`.

**Comment by sekur** [comment]
I'll mark this closed, please confirm when possible.  Thanks!
