### ISSUE TITLE
schema compile does not generate enumeration enum correctly

### ISSUE THREAD

**Issue by javadoug** [corenova/yang-forge#9]
Per [rfc6020/enum/value statement](https://tools.ietf.org/html/rfc6020#section-9.6.4.2) enum with no value sub statement should automatically generate one. I'm not sure if this is a bug for the compiler or not but I expected the output to at least show the enum value statement.

The example enum was taken from rfc.

Steps to reproduce issue:

schema.yang

```
module hello-world {
  description "a test";
  leaf hello { type string; default "world"; }
  leaf myenum {
    type enumeration {
      enum zero;
      enum one;
      enum seven {
        value 7;
      }
    }
  }
}
```

run

```
yfc schema -c schema.yang -f json

Output:
{
  "module": {
    "hello-world": {
      "description": "a test",
      "leaf": {
        "hello": {
          "type": "string",
          "default": "world"
        },
        "myenum": {
          "type": {
            "enumeration": {
              "enum": {
                "seven": {
                  "value": "7"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

Notice that enum value `zero` and `one` are missing in output.

**Comment by sekur** [comment]
@javadoug thanks for reporting this issue.  you're right, the compiler was not yet handling the auto value assignment for the enumeration types.  In addition, the `schema` command was simply outputting the `parse` results and not the `compile` results.  I'm working on this now, but I will likely need to alter the output format a bit to capture the compiled output.  I'll update and you can then change how you are consuming the JSON output for your needs.

**Comment by sekur** [comment]
@javadoug latest commit should address this issue. it's also been published into npm as version 0.9.16. please check/confirm when possible.

**Comment by sekur** [comment]
I'll mark this closed.  Please confirm when possible, thanks!

**Comment by javadoug** [comment]
@saintkepha Yes, that works. Thanks. I notice the output now includes non-JSON data when the -f json flag is set which breaks my scripts which depend on JSON parseable output. 

```
    yfc schema -c schema.yang -f json >./schema.json

    output:

    executing rpc run...
    executing rpc schema...
    {
     "synth": "source",
     "name": "nsd",
     "schema": { ... }
     ...
    }
```

The fix/workaround is to use the `-o` option instead of capturing the output from the cmd line.
`yfc schema -c schema.yang -f json -o ./schema.json`

**Comment by sekur** [comment]
Which version?  I thought I squashed that one in the latest publish but will take another look. 

Thanks!

**Comment by javadoug** [comment]
yfc -V 
0.10.42

**Comment by sekur** [comment]
BTW - I've changed the behaviors a bit so --preprocess (-p) would likely get you the result you're looking for whereas --compile would generate YF executable file (which includes much more metadata).

**Comment by sekur** [comment]
ok, fixed and published 0.10.43

looks like the fix was only on my local repo. :-)

**Comment by javadoug** [comment]
@saintkepha Yes, that fixes the non-JSON output issue, I complained about. Thank you. 

The -p was a good suggestion, I like that -c gives me the "dependencies" collection so I can resolve referenced types. But yes, -p was more like what I got before this bug. So far, very pleased with the improvements.

**Comment by sekur** [comment]
Glad to hear it's been useful! :-)

Currently working on the next branch 0.11.x, need to pay off some technical debt on bundling way too many optional dependencies within YF and adding support for some more missing YANG statements.

One key enhancement will be supporting multiple schemas in a given "app bundle" so that I can unlock external module augment statements.  Another is the new "translate" RPC which will provide data format validation/conversion of actual config data across formats. 

BTW, have you tried using YF programmatically?  I really need to improve user docs on it but would welcome feedback/suggestions on how best to document it. 

Thanks,

Peter Lee
